USE [master]
GO

/****** Object:  Database [DemoCRUD0]    Script Date: 3/22/2021 1:39:15 PM ******/
CREATE DATABASE [DemoCRUD0]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoCRUD0', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DemoCRUD0.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DemoCRUD0_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DemoCRUD0_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DemoCRUD0] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoCRUD0].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoCRUD0] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoCRUD0] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoCRUD0] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoCRUD0] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoCRUD0] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoCRUD0] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoCRUD0] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoCRUD0] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoCRUD0] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoCRUD0] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoCRUD0] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoCRUD0] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoCRUD0] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoCRUD0] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoCRUD0] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DemoCRUD0] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoCRUD0] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoCRUD0] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoCRUD0] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoCRUD0] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoCRUD0] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DemoCRUD0] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoCRUD0] SET RECOVERY FULL 
GO

ALTER DATABASE [DemoCRUD0] SET  MULTI_USER 
GO

ALTER DATABASE [DemoCRUD0] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoCRUD0] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoCRUD0] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoCRUD0] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DemoCRUD0] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DemoCRUD0] SET  READ_WRITE 
GO

